const char* pokemons[] = {
"none",
"bulbasaur",
"ivysaur",
"venusaur",
"charmander",
"charmeleon",
"charizard",
"squirtle",
"wartortle",
"blastoise",
"caterpie",
"metapod",
"butterfree",
"weedle",
"kakuna",
"beedrill",
"pidgey",
"pidgeotto",
"pidgeot",
"rattata",
"raticate",
"spearow",
"fearow",
"ekans",
"arbok",
"pikachu",
"raichu",
"sandshrew",
"sandslash",
"nidoran-f",
"nidorina",
"nidoqueen",
"nidoran-m",
"nidorino",
"nidoking",
"clefairy",
"clefable",
"vulpix",
"ninetales",
"jigglypuff",
"wigglytuff",
"zubat",
"golbat",
"oddish",
"gloom",
"vileplume",
"paras",
"parasect",
"venonat",
"venomoth",
"diglett",
"dugtrio",
"meowth",
"persian",
"psyduck",
"golduck",
"mankey",
"primeape",
"growlithe",
"arcanine",
"poliwag",
"poliwhirl",
"poliwrath",
"abra",
"kadabra",
"alakazam",
"machop",
"machoke",
"machamp",
"bellsprout",
"weepinbell",
"victreebel",
"tentacool",
"tentacruel",
"geodude",
"graveler",
"golem",
"ponyta",
"rapidash",
"slowpoke",
"slowbro",
"magnemite",
"magneton",
"farfetchd",
"doduo",
"dodrio",
"seel",
"dewgong",
"grimer",
"muk",
"shellder",
"cloyster",
"gastly",
"haunter",
"gengar",
"onix",
"drowzee",
"hypno",
"krabby",
"kingler",
"voltorb",
"electrode",
"exeggcute",
"exeggutor",
"cubone",
"marowak",
"hitmonlee",
"hitmonchan",
"lickitung",
"koffing",
"weezing",
"rhyhorn",
"rhydon",
"chansey",
"tangela",
"kangaskhan",
"horsea",
"seadra",
"goldeen",
"seaking",
"staryu",
"starmie",
"mr-mime",
"scyther",
"jynx",
"electabuzz",
"magmar",
"pinsir",
"tauros",
"magikarp",
"gyarados",
"lapras",
"ditto",
"eevee",
"vaporeon",
"jolteon",
"flareon",
"porygon",
"omanyte",
"omastar",
"kabuto",
"kabutops",
"aerodactyl",
"snorlax",
"articuno",
"zapdos",
"moltres",
"dratini",
"dragonair",
"dragonite",
"mewtwo",
"mew",
"chikorita",
"bayleef",
"meganium",
"cyndaquil",
"quilava",
"typhlosion",
"totodile",
"croconaw",
"feraligatr",
"sentret",
"furret",
"hoothoot",
"noctowl",
"ledyba",
"ledian",
"spinarak",
"ariados",
"crobat",
"chinchou",
"lanturn",
"pichu",
"cleffa",
"igglybuff",
"togepi",
"togetic",
"natu",
"xatu",
"mareep",
"flaaffy",
"ampharos",
"bellossom",
"marill",
"azumarill",
"sudowoodo",
"politoed",
"hoppip",
"skiploom",
"jumpluff",
"aipom",
"sunkern",
"sunflora",
"yanma",
"wooper",
"quagsire",
"espeon",
"umbreon",
"murkrow",
"slowking",
"misdreavus",
"unown",
"wobbuffet",
"girafarig",
"pineco",
"forretress",
"dunsparce",
"gligar",
"steelix",
"snubbull",
"granbull",
"qwilfish",
"scizor",
"shuckle",
"heracross",
"sneasel",
"teddiursa",
"ursaring",
"slugma",
"magcargo",
"swinub",
"piloswine",
"corsola",
"remoraid",
"octillery",
"delibird",
"mantine",
"skarmory",
"houndour",
"houndoom",
"kingdra",
"phanpy",
"donphan",
"porygon2",
"stantler",
"smeargle",
"tyrogue",
"hitmontop",
"smoochum",
"elekid",
"magby",
"miltank",
"blissey",
"raikou",
"entei",
"suicune",
"larvitar",
"pupitar",
"tyranitar",
"lugia",
"ho-oh",
"celebi",
"treecko",
"grovyle",
"sceptile",
"torchic",
"combusken",
"blaziken",
"mudkip",
"marshtomp",
"swampert",
"poochyena",
"mightyena",
"zigzagoon",
"linoone",
"wurmple",
"silcoon",
"beautifly",
"cascoon",
"dustox",
"lotad",
"lombre",
"ludicolo",
"seedot",
"nuzleaf",
"shiftry",
"taillow",
"swellow",
"wingull",
"pelipper",
"ralts",
"kirlia",
"gardevoir",
"surskit",
"masquerain",
"shroomish",
"breloom",
"slakoth",
"vigoroth",
"slaking",
"nincada",
"ninjask",
"shedinja",
"whismur",
"loudred",
"exploud",
"makuhita",
"hariyama",
"azurill",
"nosepass",
"skitty",
"delcatty",
"sableye",
"mawile",
"aron",
"lairon",
"aggron",
"meditite",
"medicham",
"electrike",
"manectric",
"plusle",
"minun",
"volbeat",
"illumise",
"roselia",
"gulpin",
"swalot",
"carvanha",
"sharpedo",
"wailmer",
"wailord",
"numel",
"camerupt",
"torkoal",
"spoink",
"grumpig",
"spinda",
"trapinch",
"vibrava",
"flygon",
"cacnea",
"cacturne",
"swablu",
"altaria",
"zangoose",
"seviper",
"lunatone",
"solrock",
"barboach",
"whiscash",
"corphish",
"crawdaunt",
"baltoy",
"claydol",
"lileep",
"cradily",
"anorith",
"armaldo",
"feebas",
"milotic",
"castform",
"kecleon",
"shuppet",
"banette",
"duskull",
"dusclops",
"tropius",
"chimecho",
"absol",
"wynaut",
"snorunt",
"glalie",
"spheal",
"sealeo",
"walrein",
"clamperl",
"huntail",
"gorebyss",
"relicanth",
"luvdisc",
"bagon",
"shelgon",
"salamence",
"beldum",
"metang",
"metagross",
"regirock",
"regice",
"registeel",
"latias",
"latios",
"kyogre",
"groudon",
"rayquaza",
"jirachi",
"deoxys",
"turtwig",
"grotle",
"torterra",
"chimchar",
"monferno",
"infernape",
"piplup",
"prinplup",
"empoleon",
"starly",
"staravia",
"staraptor",
"bidoof",
"bibarel",
"kricketot",
"kricketune",
"shinx",
"luxio",
"luxray",
"budew",
"roserade",
"cranidos",
"rampardos",
"shieldon",
"bastiodon",
"burmy",
"wormadam",
"mothim",
"combee",
"vespiquen",
"pachirisu",
"buizel",
"floatzel",
"cherubi",
"cherrim",
"shellos",
"gastrodon",
"ambipom",
"drifloon",
"drifblim",
"buneary",
"lopunny",
"mismagius",
"honchkrow",
"glameow",
"purugly",
"chingling",
"stunky",
"skuntank",
"bronzor",
"bronzong",
"bonsly",
"mime-jr",
"happiny",
"chatot",
"spiritomb",
"gible",
"gabite",
"garchomp",
"munchlax",
"riolu",
"lucario",
"hippopotas",
"hippowdon",
"skorupi",
"drapion",
"croagunk",
"toxicroak",
"carnivine",
"finneon",
"lumineon",
"mantyke",
"snover",
"abomasnow",
"weavile",
"magnezone",
"lickilicky",
"rhyperior",
"tangrowth",
"electivire",
"magmortar",
"togekiss",
"yanmega",
"leafeon",
"glaceon",
"gliscor",
"mamoswine",
"porygon-z",
"gallade",
"probopass",
"dusknoir",
"froslass",
"rotom",
"uxie",
"mesprit",
"azelf",
"dialga",
"palkia",
"heatran",
"regigigas",
"giratina",
"cresselia",
"phione",
"manaphy",
"darkrai",
"shaymin",
"arceus",
};


// const char* pokemons[] = {
// "none",
// "bulbasaur",
// "ivysaur",
// "venusaur",
// "charmander",
// "charmeleon",
// "charizard",
// "squirtle",
// "wartortle",
// "blastoise",
// "caterpie",
// "metapod",
// "butterfree",
// "weedle",
// "kakuna",
// "beedrill",
// "pidgey",
// "pidgeotto",
// "pidgeot",
// "rattata",
// "raticate",
// "spearow",
// "fearow",
// "ekans",
// "arbok",
// "pikachu",
// "raichu",
// "sandshrew",
// "sandslash",
// "nidoran-f",
// "nidorina",
// "nidoqueen",
// "nidoran-m",
// "nidorino",
// "nidoking",
// "clefairy",
// "clefable",
// "vulpix",
// "ninetales",
// "jigglypuff",
// "wigglytuff",
// "zubat",
// "golbat",
// "oddish",
// "gloom",
// "vileplume",
// "paras",
// "parasect",
// "venonat",
// "venomoth",
// "diglett",
// "dugtrio",
// "meowth",
// "persian",
// "psyduck",
// "golduck",
// "mankey",
// "primeape",
// "growlithe",
// "arcanine",
// "poliwag",
// "poliwhirl",
// "poliwrath",
// "abra",
// "kadabra",
// "alakazam",
// "machop",
// "machoke",
// "machamp",
// "bellsprout",
// "weepinbell",
// "victreebel",
// "tentacool",
// "tentacruel",
// "geodude",
// "graveler",
// "golem",
// "ponyta",
// "rapidash",
// "slowpoke",
// "slowbro",
// "magnemite",
// "magneton",
// "farfetchd",
// "doduo",
// "dodrio",
// "seel",
// "dewgong",
// "grimer",
// "muk",
// "shellder",
// "cloyster",
// "gastly",
// "haunter",
// "gengar",
// "onix",
// "drowzee",
// "hypno",
// "krabby",
// "kingler",
// "voltorb",
// "electrode",
// "exeggcute",
// "exeggutor",
// "cubone",
// "marowak",
// "hitmonlee",
// "hitmonchan",
// "lickitung",
// "koffing",
// "weezing",
// "rhyhorn",
// "rhydon",
// "chansey",
// "tangela",
// "kangaskhan",
// "horsea",
// "seadra",
// "goldeen",
// "seaking",
// "staryu",
// "starmie",
// "mr-mime",
// "scyther",
// "jynx",
// "electabuzz",
// "magmar",
// "pinsir",
// "tauros",
// "magikarp",
// "gyarados",
// "lapras",
// "ditto",
// "eevee",
// "vaporeon",
// "jolteon",
// "flareon",
// "porygon",
// "omanyte",
// "omastar",
// "kabuto",
// "kabutops",
// "aerodactyl",
// "snorlax",
// "articuno",
// "zapdos",
// "moltres",
// "dratini",
// "dragonair",
// "dragonite",
// "mewtwo",
// "mew",
// "chikorita",
// "bayleef",
// "meganium",
// "cyndaquil",
// "quilava",
// "typhlosion",
// "totodile",
// "croconaw",
// "feraligatr",
// "sentret",
// "furret",
// "hoothoot",
// "noctowl",
// "ledyba",
// "ledian",
// "spinarak",
// "ariados",
// "crobat",
// "chinchou",
// "lanturn",
// "pichu",
// "cleffa",
// "igglybuff",
// "togepi",
// "togetic",
// "natu",
// "xatu",
// "mareep",
// "flaaffy",
// "ampharos",
// "bellossom",
// "marill",
// "azumarill",
// "sudowoodo",
// "politoed",
// "hoppip",
// "skiploom",
// "jumpluff",
// "aipom",
// "sunkern",
// "sunflora",
// "yanma",
// "wooper",
// "quagsire",
// "espeon",
// "umbreon",
// "murkrow",
// "slowking",
// "misdreavus",
// "unown-A",
// "unown-B",
// "unown-C",
// "unown-D",
// "unown-E",
// "unown-F",
// "unown-G",
// "unown-H",
// "unown-I",
// "unown-J",
// "unown-K",
// "unown-L",
// "unown-M",
// "unown-N",
// "unown-O",
// "unown-P",
// "unown-Q",
// "unown-R",
// "unown-S",
// "unown-T",
// "unown-U",
// "unown-V",
// "unown-W",
// "unown-X",
// "unown-Y",
// "unown-Z",
// "unown-exclamation",
// "unown-question",
// "wobbuffet",
// "girafarig",
// "pineco",
// "forretress",
// "dunsparce",
// "gligar",
// "steelix",
// "snubbull",
// "granbull",
// "qwilfish",
// "scizor",
// "shuckle",
// "heracross",
// "sneasel",
// "teddiursa",
// "ursaring",
// "slugma",
// "magcargo",
// "swinub",
// "piloswine",
// "corsola",
// "remoraid",
// "octillery",
// "delibird",
// "mantine",
// "skarmory",
// "houndour",
// "houndoom",
// "kingdra",
// "phanpy",
// "donphan",
// "porygon2",
// "stantler",
// "smeargle",
// "tyrogue",
// "hitmontop",
// "smoochum",
// "elekid",
// "magby",
// "miltank",
// "blissey",
// "raikou",
// "entei",
// "suicune",
// "larvitar",
// "pupitar",
// "tyranitar",
// "lugia",
// "ho-oh",
// "celebi",
// "treecko",
// "grovyle",
// "sceptile",
// "torchic",
// "combusken",
// "blaziken",
// "mudkip",
// "marshtomp",
// "swampert",
// "poochyena",
// "mightyena",
// "zigzagoon",
// "linoone",
// "wurmple",
// "silcoon",
// "beautifly",
// "cascoon",
// "dustox",
// "lotad",
// "lombre",
// "ludicolo",
// "seedot",
// "nuzleaf",
// "shiftry",
// "taillow",
// "swellow",
// "wingull",
// "pelipper",
// "ralts",
// "kirlia",
// "gardevoir",
// "surskit",
// "masquerain",
// "shroomish",
// "breloom",
// "slakoth",
// "vigoroth",
// "slaking",
// "nincada",
// "ninjask",
// "shedinja",
// "whismur",
// "loudred",
// "exploud",
// "makuhita",
// "hariyama",
// "azurill",
// "nosepass",
// "skitty",
// "delcatty",
// "sableye",
// "mawile",
// "aron",
// "lairon",
// "aggron",
// "meditite",
// "medicham",
// "electrike",
// "manectric",
// "plusle",
// "minun",
// "volbeat",
// "illumise",
// "roselia",
// "gulpin",
// "swalot",
// "carvanha",
// "sharpedo",
// "wailmer",
// "wailord",
// "numel",
// "camerupt",
// "torkoal",
// "spoink",
// "grumpig",
// "spinda",
// "trapinch",
// "vibrava",
// "flygon",
// "cacnea",
// "cacturne",
// "swablu",
// "altaria",
// "zangoose",
// "seviper",
// "lunatone",
// "solrock",
// "barboach",
// "whiscash",
// "corphish",
// "crawdaunt",
// "baltoy",
// "claydol",
// "lileep",
// "cradily",
// "anorith",
// "armaldo",
// "feebas",
// "milotic",
// "castform",
// "kecleon",
// "shuppet",
// "banette",
// "duskull",
// "dusclops",
// "tropius",
// "chimecho",
// "absol",
// "wynaut",
// "snorunt",
// "glalie",
// "spheal",
// "sealeo",
// "walrein",
// "clamperl",
// "huntail",
// "gorebyss",
// "relicanth",
// "luvdisc",
// "bagon",
// "shelgon",
// "salamence",
// "beldum",
// "metang",
// "metagross",
// "regirock",
// "regice",
// "registeel",
// "latias",
// "latios",
// "kyogre",
// "groudon",
// "rayquaza",
// "jirachi",
// "deoxys-normal",
// "deoxys-attack",
// "deoxys-defense",
// "deoxys-speed",
// "turtwig",
// "grotle",
// "torterra",
// "chimchar",
// "monferno",
// "infernape",
// "piplup",
// "prinplup",
// "empoleon",
// "starly",
// "staravia",
// "staraptor",
// "bidoof",
// "bibarel",
// "kricketot",
// "kricketune",
// "shinx",
// "luxio",
// "luxray",
// "budew",
// "roserade",
// "cranidos",
// "rampardos",
// "shieldon",
// "bastiodon",
// "burmy-plant",
// "burmy-sandy",
// "burmy-trash",
// "wormadan-plant",
// "wormadan-sandy",
// "wormadan-trash",
// "mothim",
// "combee",
// "vespiquen",
// "pachirisu",
// "buizel",
// "floatzel",
// "cherubi",
// "cherrim",
// "shellos-west",
// "shellos-east",
// "gastrodon-west",
// "gastrodon-east",
// "ambipom",
// "drifloon",
// "drifblim",
// "buneary",
// "lopunny",
// "mismagius",
// "honchkrow",
// "glameow",
// "purugly",
// "chingling",
// "stunky",
// "skuntank",
// "bronzor",
// "bronzong",
// "bonsly",
// "mime-jr",
// "happiny",
// "chatot",
// "spiritomb",
// "gible",
// "gabite",
// "garchomp",
// "munchlax",
// "riolu",
// "lucario",
// "hippopotas",
// "hippowdon",
// "skorupi",
// "drapion",
// "croagunk",
// "toxicroak",
// "carnivine",
// "finneon",
// "lumineon",
// "mantyke",
// "snover",
// "abomasnow",
// "weavile",
// "magnezone",
// "lickilicky",
// "rhyperior",
// "tangrowth",
// "electivire",
// "magmortar",
// "togekiss",
// "yanmega",
// "leafeon",
// "glaceon",
// "gliscor",
// "mamoswine",
// "porygon-z",
// "gallade",
// "probopass",
// "dusknoir",
// "froslass",
// "rotom",
// "uxie",
// "mesprit",
// "azelf",
// "dialga",
// "palkia",
// "heatran",
// "regigigas",
// "giratina",
// "cresselia",
// "phione",
// "manaphy",
// "darkrai",
// "shaymin",
// "arceus",
// };

#include <stdio.h>

int main(void) {
    
    const int
    sprite_width = 32,
    sprite_height = 32,
    sprite_height_inc = 33,
    sprite_width_inc = 33,
    img_width = 989,
    img_height = 592,
    width_ratio = img_width / sprite_width;

    //Pokemon with multiple forms in the spritesheet
    const int 
    unown_index = 201,
    unown_count = 28, //Alphabet + ! and ?
    
    deoxys_index = 386,
    deoxys_count = 4,
    
    burmy_index = 412,
    burmy_count = 3,
    
    wormadan_index = 413,
    wormadan_count = 3,
    
    shellos_index = 422,
    shellos_count = 2,
    
    gastrodon_index = 423,
    gastrodon_count = 2;

    int cur_width = 0, cur_height = 0;

    size_t pokemon_count = sizeof(pokemons) / sizeof(pokemons[0]);

    printf(
        ".pokesprite { display: inline-block }\n"
        ".pokesprite.pokemon { width: %ipx; height: %ipx; background: url('pokesprite-pokemon-gen4.png'); image-rendering: pixelated; image-rendering: -moz-crisp-edges }\n\n",
    sprite_width, sprite_height);

    for (size_t i = 0; i < pokemon_count; i++) {
        printf(".pokesprite.%s { background-position: -%ipx -%ipx }\n", pokemons[i], cur_width, cur_height);
        
        if (i == unown_index) {
            for (int j = 0; j < unown_count; j++) {
                cur_width += sprite_width_inc;
                if (cur_width >= img_width) {
                    cur_width = 0;
                    cur_height += sprite_height_inc;
                }
            }
            continue;
        }
        if (i == deoxys_index) {
            for (int j = 0; j < deoxys_count; j++) {
                cur_width += sprite_width_inc;
                if (cur_width >= img_width) {
                    cur_width = 0;
                    cur_height += sprite_height_inc;
                }
            }
            continue;
        }
        if (i == burmy_index) {
            for (int j = 0; j < burmy_count; j++) {
                cur_width += sprite_width_inc;
                if (cur_width >= img_width) {
                    cur_width = 0;
                    cur_height += sprite_height_inc;
                }
            }
            continue;
        }
        if (i == wormadan_index) {
            for (int j = 0; j < wormadan_count; j++) {
                cur_width += sprite_width_inc;
                if (cur_width >= img_width) {
                    cur_width = 0;
                    cur_height += sprite_height_inc;
                }
            }
            continue;
        }
        if (i == shellos_index) {
            for (int j = 0; j < shellos_count; j++) {
                cur_width += sprite_width_inc;
                if (cur_width >= img_width) {
                    cur_width = 0;
                    cur_height += sprite_height_inc;
                }
            }
            continue;
        }
        if (i == gastrodon_index) {
            for (int j = 0; j < gastrodon_count; j++) {
                cur_width += sprite_width_inc;
                if (cur_width >= img_width) {
                    cur_width = 0;
                    cur_height += sprite_height_inc;
                }
            }
            continue;
        }

        cur_width += sprite_width_inc;
        if (cur_width >= img_width) {
            cur_width = 0;
            cur_height += sprite_height_inc;
        }
    }
    return 0;
}