#ifndef POKEMON_DATA
#define POKEMON_DATA
/*
List of all Pokemon available in generation 4, ordered by Pokedex number.
*/
const char* pokemons[] = {
"none",
"bulbasaur",
"ivysaur",
"venusaur",
"charmander",
"charmeleon",
"charizard",
"squirtle",
"wartortle",
"blastoise",
"caterpie",
"metapod",
"butterfree",
"weedle",
"kakuna",
"beedrill",
"pidgey",
"pidgeotto",
"pidgeot",
"rattata",
"raticate",
"spearow",
"fearow",
"ekans",
"arbok",
"pikachu",
"raichu",
"sandshrew",
"sandslash",
"nidoran-f",
"nidorina",
"nidoqueen",
"nidoran-m",
"nidorino",
"nidoking",
"clefairy",
"clefable",
"vulpix",
"ninetales",
"jigglypuff",
"wigglytuff",
"zubat",
"golbat",
"oddish",
"gloom",
"vileplume",
"paras",
"parasect",
"venonat",
"venomoth",
"diglett",
"dugtrio",
"meowth",
"persian",
"psyduck",
"golduck",
"mankey",
"primeape",
"growlithe",
"arcanine",
"poliwag",
"poliwhirl",
"poliwrath",
"abra",
"kadabra",
"alakazam",
"machop",
"machoke",
"machamp",
"bellsprout",
"weepinbell",
"victreebel",
"tentacool",
"tentacruel",
"geodude",
"graveler",
"golem",
"ponyta",
"rapidash",
"slowpoke",
"slowbro",
"magnemite",
"magneton",
"farfetchd",
"doduo",
"dodrio",
"seel",
"dewgong",
"grimer",
"muk",
"shellder",
"cloyster",
"gastly",
"haunter",
"gengar",
"onix",
"drowzee",
"hypno",
"krabby",
"kingler",
"voltorb",
"electrode",
"exeggcute",
"exeggutor",
"cubone",
"marowak",
"hitmonlee",
"hitmonchan",
"lickitung",
"koffing",
"weezing",
"rhyhorn",
"rhydon",
"chansey",
"tangela",
"kangaskhan",
"horsea",
"seadra",
"goldeen",
"seaking",
"staryu",
"starmie",
"mr-mime",
"scyther",
"jynx",
"electabuzz",
"magmar",
"pinsir",
"tauros",
"magikarp",
"gyarados",
"lapras",
"ditto",
"eevee",
"vaporeon",
"jolteon",
"flareon",
"porygon",
"omanyte",
"omastar",
"kabuto",
"kabutops",
"aerodactyl",
"snorlax",
"articuno",
"zapdos",
"moltres",
"dratini",
"dragonair",
"dragonite",
"mewtwo",
"mew",
"chikorita",
"bayleef",
"meganium",
"cyndaquil",
"quilava",
"typhlosion",
"totodile",
"croconaw",
"feraligatr",
"sentret",
"furret",
"hoothoot",
"noctowl",
"ledyba",
"ledian",
"spinarak",
"ariados",
"crobat",
"chinchou",
"lanturn",
"pichu",
"cleffa",
"igglybuff",
"togepi",
"togetic",
"natu",
"xatu",
"mareep",
"flaaffy",
"ampharos",
"bellossom",
"marill",
"azumarill",
"sudowoodo",
"politoed",
"hoppip",
"skiploom",
"jumpluff",
"aipom",
"sunkern",
"sunflora",
"yanma",
"wooper",
"quagsire",
"espeon",
"umbreon",
"murkrow",
"slowking",
"misdreavus",
"unown",
"wobbuffet",
"girafarig",
"pineco",
"forretress",
"dunsparce",
"gligar",
"steelix",
"snubbull",
"granbull",
"qwilfish",
"scizor",
"shuckle",
"heracross",
"sneasel",
"teddiursa",
"ursaring",
"slugma",
"magcargo",
"swinub",
"piloswine",
"corsola",
"remoraid",
"octillery",
"delibird",
"mantine",
"skarmory",
"houndour",
"houndoom",
"kingdra",
"phanpy",
"donphan",
"porygon2",
"stantler",
"smeargle",
"tyrogue",
"hitmontop",
"smoochum",
"elekid",
"magby",
"miltank",
"blissey",
"raikou",
"entei",
"suicune",
"larvitar",
"pupitar",
"tyranitar",
"lugia",
"ho-oh",
"celebi",
"treecko",
"grovyle",
"sceptile",
"torchic",
"combusken",
"blaziken",
"mudkip",
"marshtomp",
"swampert",
"poochyena",
"mightyena",
"zigzagoon",
"linoone",
"wurmple",
"silcoon",
"beautifly",
"cascoon",
"dustox",
"lotad",
"lombre",
"ludicolo",
"seedot",
"nuzleaf",
"shiftry",
"taillow",
"swellow",
"wingull",
"pelipper",
"ralts",
"kirlia",
"gardevoir",
"surskit",
"masquerain",
"shroomish",
"breloom",
"slakoth",
"vigoroth",
"slaking",
"nincada",
"ninjask",
"shedinja",
"whismur",
"loudred",
"exploud",
"makuhita",
"hariyama",
"azurill",
"nosepass",
"skitty",
"delcatty",
"sableye",
"mawile",
"aron",
"lairon",
"aggron",
"meditite",
"medicham",
"electrike",
"manectric",
"plusle",
"minun",
"volbeat",
"illumise",
"roselia",
"gulpin",
"swalot",
"carvanha",
"sharpedo",
"wailmer",
"wailord",
"numel",
"camerupt",
"torkoal",
"spoink",
"grumpig",
"spinda",
"trapinch",
"vibrava",
"flygon",
"cacnea",
"cacturne",
"swablu",
"altaria",
"zangoose",
"seviper",
"lunatone",
"solrock",
"barboach",
"whiscash",
"corphish",
"crawdaunt",
"baltoy",
"claydol",
"lileep",
"cradily",
"anorith",
"armaldo",
"feebas",
"milotic",
"castform",
"kecleon",
"shuppet",
"banette",
"duskull",
"dusclops",
"tropius",
"chimecho",
"absol",
"wynaut",
"snorunt",
"glalie",
"spheal",
"sealeo",
"walrein",
"clamperl",
"huntail",
"gorebyss",
"relicanth",
"luvdisc",
"bagon",
"shelgon",
"salamence",
"beldum",
"metang",
"metagross",
"regirock",
"regice",
"registeel",
"latias",
"latios",
"kyogre",
"groudon",
"rayquaza",
"jirachi",
"deoxys",
"turtwig",
"grotle",
"torterra",
"chimchar",
"monferno",
"infernape",
"piplup",
"prinplup",
"empoleon",
"starly",
"staravia",
"staraptor",
"bidoof",
"bibarel",
"kricketot",
"kricketune",
"shinx",
"luxio",
"luxray",
"budew",
"roserade",
"cranidos",
"rampardos",
"shieldon",
"bastiodon",
"burmy",
"wormadam",
"mothim",
"combee",
"vespiquen",
"pachirisu",
"buizel",
"floatzel",
"cherubi",
"cherrim",
"shellos",
"gastrodon",
"ambipom",
"drifloon",
"drifblim",
"buneary",
"lopunny",
"mismagius",
"honchkrow",
"glameow",
"purugly",
"chingling",
"stunky",
"skuntank",
"bronzor",
"bronzong",
"bonsly",
"mime-jr",
"happiny",
"chatot",
"spiritomb",
"gible",
"gabite",
"garchomp",
"munchlax",
"riolu",
"lucario",
"hippopotas",
"hippowdon",
"skorupi",
"drapion",
"croagunk",
"toxicroak",
"carnivine",
"finneon",
"lumineon",
"mantyke",
"snover",
"abomasnow",
"weavile",
"magnezone",
"lickilicky",
"rhyperior",
"tangrowth",
"electivire",
"magmortar",
"togekiss",
"yanmega",
"leafeon",
"glaceon",
"gliscor",
"mamoswine",
"porygon-z",
"gallade",
"probopass",
"dusknoir",
"froslass",
"rotom",
"uxie",
"mesprit",
"azelf",
"dialga",
"palkia",
"heatran",
"regigigas",
"giratina",
"cresselia",
"phione",
"manaphy",
"darkrai",
"shaymin",
"arceus",
};

/*
Same list but with all forms.
*/
// const char* pokemons[] = {
// "none",
// "bulbasaur",
// "ivysaur",
// "venusaur",
// "charmander",
// "charmeleon",
// "charizard",
// "squirtle",
// "wartortle",
// "blastoise",
// "caterpie",
// "metapod",
// "butterfree",
// "weedle",
// "kakuna",
// "beedrill",
// "pidgey",
// "pidgeotto",
// "pidgeot",
// "rattata",
// "raticate",
// "spearow",
// "fearow",
// "ekans",
// "arbok",
// "pikachu",
// "raichu",
// "sandshrew",
// "sandslash",
// "nidoran-f",
// "nidorina",
// "nidoqueen",
// "nidoran-m",
// "nidorino",
// "nidoking",
// "clefairy",
// "clefable",
// "vulpix",
// "ninetales",
// "jigglypuff",
// "wigglytuff",
// "zubat",
// "golbat",
// "oddish",
// "gloom",
// "vileplume",
// "paras",
// "parasect",
// "venonat",
// "venomoth",
// "diglett",
// "dugtrio",
// "meowth",
// "persian",
// "psyduck",
// "golduck",
// "mankey",
// "primeape",
// "growlithe",
// "arcanine",
// "poliwag",
// "poliwhirl",
// "poliwrath",
// "abra",
// "kadabra",
// "alakazam",
// "machop",
// "machoke",
// "machamp",
// "bellsprout",
// "weepinbell",
// "victreebel",
// "tentacool",
// "tentacruel",
// "geodude",
// "graveler",
// "golem",
// "ponyta",
// "rapidash",
// "slowpoke",
// "slowbro",
// "magnemite",
// "magneton",
// "farfetchd",
// "doduo",
// "dodrio",
// "seel",
// "dewgong",
// "grimer",
// "muk",
// "shellder",
// "cloyster",
// "gastly",
// "haunter",
// "gengar",
// "onix",
// "drowzee",
// "hypno",
// "krabby",
// "kingler",
// "voltorb",
// "electrode",
// "exeggcute",
// "exeggutor",
// "cubone",
// "marowak",
// "hitmonlee",
// "hitmonchan",
// "lickitung",
// "koffing",
// "weezing",
// "rhyhorn",
// "rhydon",
// "chansey",
// "tangela",
// "kangaskhan",
// "horsea",
// "seadra",
// "goldeen",
// "seaking",
// "staryu",
// "starmie",
// "mr-mime",
// "scyther",
// "jynx",
// "electabuzz",
// "magmar",
// "pinsir",
// "tauros",
// "magikarp",
// "gyarados",
// "lapras",
// "ditto",
// "eevee",
// "vaporeon",
// "jolteon",
// "flareon",
// "porygon",
// "omanyte",
// "omastar",
// "kabuto",
// "kabutops",
// "aerodactyl",
// "snorlax",
// "articuno",
// "zapdos",
// "moltres",
// "dratini",
// "dragonair",
// "dragonite",
// "mewtwo",
// "mew",
// "chikorita",
// "bayleef",
// "meganium",
// "cyndaquil",
// "quilava",
// "typhlosion",
// "totodile",
// "croconaw",
// "feraligatr",
// "sentret",
// "furret",
// "hoothoot",
// "noctowl",
// "ledyba",
// "ledian",
// "spinarak",
// "ariados",
// "crobat",
// "chinchou",
// "lanturn",
// "pichu",
// "cleffa",
// "igglybuff",
// "togepi",
// "togetic",
// "natu",
// "xatu",
// "mareep",
// "flaaffy",
// "ampharos",
// "bellossom",
// "marill",
// "azumarill",
// "sudowoodo",
// "politoed",
// "hoppip",
// "skiploom",
// "jumpluff",
// "aipom",
// "sunkern",
// "sunflora",
// "yanma",
// "wooper",
// "quagsire",
// "espeon",
// "umbreon",
// "murkrow",
// "slowking",
// "misdreavus",
// "unown-A",
// "unown-B",
// "unown-C",
// "unown-D",
// "unown-E",
// "unown-F",
// "unown-G",
// "unown-H",
// "unown-I",
// "unown-J",
// "unown-K",
// "unown-L",
// "unown-M",
// "unown-N",
// "unown-O",
// "unown-P",
// "unown-Q",
// "unown-R",
// "unown-S",
// "unown-T",
// "unown-U",
// "unown-V",
// "unown-W",
// "unown-X",
// "unown-Y",
// "unown-Z",
// "unown-exclamation",
// "unown-question",
// "wobbuffet",
// "girafarig",
// "pineco",
// "forretress",
// "dunsparce",
// "gligar",
// "steelix",
// "snubbull",
// "granbull",
// "qwilfish",
// "scizor",
// "shuckle",
// "heracross",
// "sneasel",
// "teddiursa",
// "ursaring",
// "slugma",
// "magcargo",
// "swinub",
// "piloswine",
// "corsola",
// "remoraid",
// "octillery",
// "delibird",
// "mantine",
// "skarmory",
// "houndour",
// "houndoom",
// "kingdra",
// "phanpy",
// "donphan",
// "porygon2",
// "stantler",
// "smeargle",
// "tyrogue",
// "hitmontop",
// "smoochum",
// "elekid",
// "magby",
// "miltank",
// "blissey",
// "raikou",
// "entei",
// "suicune",
// "larvitar",
// "pupitar",
// "tyranitar",
// "lugia",
// "ho-oh",
// "celebi",
// "treecko",
// "grovyle",
// "sceptile",
// "torchic",
// "combusken",
// "blaziken",
// "mudkip",
// "marshtomp",
// "swampert",
// "poochyena",
// "mightyena",
// "zigzagoon",
// "linoone",
// "wurmple",
// "silcoon",
// "beautifly",
// "cascoon",
// "dustox",
// "lotad",
// "lombre",
// "ludicolo",
// "seedot",
// "nuzleaf",
// "shiftry",
// "taillow",
// "swellow",
// "wingull",
// "pelipper",
// "ralts",
// "kirlia",
// "gardevoir",
// "surskit",
// "masquerain",
// "shroomish",
// "breloom",
// "slakoth",
// "vigoroth",
// "slaking",
// "nincada",
// "ninjask",
// "shedinja",
// "whismur",
// "loudred",
// "exploud",
// "makuhita",
// "hariyama",
// "azurill",
// "nosepass",
// "skitty",
// "delcatty",
// "sableye",
// "mawile",
// "aron",
// "lairon",
// "aggron",
// "meditite",
// "medicham",
// "electrike",
// "manectric",
// "plusle",
// "minun",
// "volbeat",
// "illumise",
// "roselia",
// "gulpin",
// "swalot",
// "carvanha",
// "sharpedo",
// "wailmer",
// "wailord",
// "numel",
// "camerupt",
// "torkoal",
// "spoink",
// "grumpig",
// "spinda",
// "trapinch",
// "vibrava",
// "flygon",
// "cacnea",
// "cacturne",
// "swablu",
// "altaria",
// "zangoose",
// "seviper",
// "lunatone",
// "solrock",
// "barboach",
// "whiscash",
// "corphish",
// "crawdaunt",
// "baltoy",
// "claydol",
// "lileep",
// "cradily",
// "anorith",
// "armaldo",
// "feebas",
// "milotic",
// "castform",
// "kecleon",
// "shuppet",
// "banette",
// "duskull",
// "dusclops",
// "tropius",
// "chimecho",
// "absol",
// "wynaut",
// "snorunt",
// "glalie",
// "spheal",
// "sealeo",
// "walrein",
// "clamperl",
// "huntail",
// "gorebyss",
// "relicanth",
// "luvdisc",
// "bagon",
// "shelgon",
// "salamence",
// "beldum",
// "metang",
// "metagross",
// "regirock",
// "regice",
// "registeel",
// "latias",
// "latios",
// "kyogre",
// "groudon",
// "rayquaza",
// "jirachi",
// "deoxys-normal",
// "deoxys-attack",
// "deoxys-defense",
// "deoxys-speed",
// "turtwig",
// "grotle",
// "torterra",
// "chimchar",
// "monferno",
// "infernape",
// "piplup",
// "prinplup",
// "empoleon",
// "starly",
// "staravia",
// "staraptor",
// "bidoof",
// "bibarel",
// "kricketot",
// "kricketune",
// "shinx",
// "luxio",
// "luxray",
// "budew",
// "roserade",
// "cranidos",
// "rampardos",
// "shieldon",
// "bastiodon",
// "burmy-plant",
// "burmy-sandy",
// "burmy-trash",
// "wormadan-plant",
// "wormadan-sandy",
// "wormadan-trash",
// "mothim",
// "combee",
// "vespiquen",
// "pachirisu",
// "buizel",
// "floatzel",
// "cherubi",
// "cherrim",
// "shellos-west",
// "shellos-east",
// "gastrodon-west",
// "gastrodon-east",
// "ambipom",
// "drifloon",
// "drifblim",
// "buneary",
// "lopunny",
// "mismagius",
// "honchkrow",
// "glameow",
// "purugly",
// "chingling",
// "stunky",
// "skuntank",
// "bronzor",
// "bronzong",
// "bonsly",
// "mime-jr",
// "happiny",
// "chatot",
// "spiritomb",
// "gible",
// "gabite",
// "garchomp",
// "munchlax",
// "riolu",
// "lucario",
// "hippopotas",
// "hippowdon",
// "skorupi",
// "drapion",
// "croagunk",
// "toxicroak",
// "carnivine",
// "finneon",
// "lumineon",
// "mantyke",
// "snover",
// "abomasnow",
// "weavile",
// "magnezone",
// "lickilicky",
// "rhyperior",
// "tangrowth",
// "electivire",
// "magmortar",
// "togekiss",
// "yanmega",
// "leafeon",
// "glaceon",
// "gliscor",
// "mamoswine",
// "porygon-z",
// "gallade",
// "probopass",
// "dusknoir",
// "froslass",
// "rotom",
// "uxie",
// "mesprit",
// "azelf",
// "dialga",
// "palkia",
// "heatran",
// "regigigas",
// "giratina",
// "cresselia",
// "phione",
// "manaphy",
// "darkrai",
// "shaymin",
// "arceus",
// };

/*
List of all Items available in generation 4, ordered by in-game item id
*/
const char* items[] = {
"none",
"master ball",
"ultra ball",
"great ball",
"poke ball",
"safari ball",
"net ball",
"dive ball",
"nest ball",
"repeat ball",
"timer ball",
"luxury ball",
"premier ball",
"dusk ball",
"heal ball",
"quick ball",
"cherish ball",
"potion",
"antidote",
"burn heal",
"ice heal",
"awakening",
"paralyze heal",
"full restore",
"max potion",
"hyper potion",
"super potion",
"full heal",
"revive",
"max revive",
"fresh water",
"soda pop",
"lemonade",
"moomoo milk iii",
"energy powder",
"energy root",
"heal powder",
"revival herb",
"ether",
"max ether",
"elixir",
"max elixir",
"lava cookie",
"berry juice",
"sacred ash",
"hp up",
"protein",
"iron",
"carbos",
"calcium",
"rare candy",
"pp up",
"zinc",
"pp max",
"old gateau",
"guard spec.",
"dire hit",
"x attack",
"x defense",
"x speed",
"x accuracy",
"x sp. atk",
"x sp. def",
"poke doll",
"fluffy tail",
"blue flute",
"yellow flute",
"red flute",
"black flute",
"white flute",
"shoal salt",
"shoal shell",
"red shard",
"blue shard",
"yellow shard",
"green shard",
"super repel",
"max repel",
"escape rope",
"repel",
"sun stone",
"moon stone",
"fire stone",
"thunder stone",
"water stone",
"leaf stone",
"tiny mushroom",
"big mushroom",
"pearl",
"big pearl",
"stardust",
"star piece",
"nugget",
"heart scale",
"honey",
"growth mulch",
"damp mulch",
"stable mulch",
"gooey mulch",
"root fossil",
"claw fossil",
"helix fossil",
"dome fossil",
"old amber",
"armor fossil",
"skull fossil",
"rare bone",
"shiny stone",
"dusk stone",
"dawn stone",
"oval stone",
"odd keystone",
"griseous orb",
"unknown",
"unknown",
"unknown",
"unknown",
"unknown",
"unknown",
"unknown",
"unknown",
"unknown",
"unknown",
"unknown",
"unknown",
"unknown",
"unknown",
"unknown",
"unknown",
"unknown",
"unknown",
"unknown",
"unknown",
"unknown",
"unknown",
"adamant orb",
"lustrous orb",
"grass mail",
"flame mail",
"bubble mail",
"bloom mail",
"tunnel mail",
"steel mail",
"heart mail",
"snow mail",
"space mail",
"air mail",
"mosaic mail",
"brick mail",
"cheri berry",
"chesto berry",
"pecha berry",
"rawst berry",
"aspear berry",
"leppa berry",
"oran berry",
"persim berry",
"lum berry",
"sitrus berry",
"figy berry",
"wiki berry",
"mago berry",
"aguav berry",
"iapapa berry",
"razz berry iii",
"bluk berry",
"nanab berry iii",
"wepear berry",
"pinap berry",
"pomeg berry",
"kelpsy berry",
"qualot berry",
"hondew berry",
"grepa berry",
"tamato berry",
"cornn berry",
"magost berry",
"rabuta berry",
"nomel berry",
"spelon berry",
"pamtre berry",
"watmel berry",
"durin berry",
"belue berry",
"occa berry",
"passho berry",
"wacan berry",
"rindo berry",
"yache berry",
"chople berry",
"kebia berry",
"shuca berry",
"coba berry",
"payapa berry",
"tanga berry",
"charti berry",
"kasib berry",
"haban berry",
"colbur berry",
"babiri berry",
"chilan berry",
"liechi berry",
"ganlon berry",
"salac berry",
"petaya berry",
"apicot berry",
"lansat berry",
"starf berry",
"enigma berry",
"micle berry",
"custap berry",
"jaboca berry",
"rowap berry",
"bright powder",
"white herb",
"macho brace",
"exp. share",
"quick claw",
"soothe bell",
"mental herb",
"choice band",
"king's rock",
"silver powder",
"amulet coin iii",
"cleanse tag",
"soul dew",
"deep sea tooth",
"deep sea scale",
"smoke ball",
"everstone",
"focus band",
"lucky egg",
"scope lens",
"metal coat",
"leftovers",
"dragon scale",
"light ball",
"soft sand",
"hard stone",
"miracle seed",
"black glasses",
"black belt",
"magnet",
"mystic water",
"sharp beak",
"poison barb",
"never-melt ice",
"spell tag",
"twisted spoon",
"charcoal",
"dragon fang",
"silk scarf",
"up-grade",
"shell bell",
"sea incense",
"lax incense",
"lucky punch",
"metal powder",
"thick club",
"stick",
"red scarf",
"blue scarf",
"pink scarf",
"green scarf",
"yellow scarf",
"wide lens",
"muscle band",
"wise glasses",
"expert belt",
"light clay",
"life orb",
"power herb",
"toxic orb",
"flame orb",
"quick powder",
"focus sash",
"zoom lens",
"metronome",
"iron ball",
"lagging tail",
"destiny knot",
"black sludge",
"icy rock",
"smooth rock",
"heat rock",
"damp rock",
"grip claw",
"choice scarf",
"sticky barb",
"power bracer",
"power belt",
"power lens",
"power band",
"power anklet",
"power weight",
"shed shell",
"big root",
"choice specs",
"flame plate",
"splash plate",
"zap plate",
"meadow plate",
"icicle plate",
"fist plate",
"toxic plate",
"earth plate",
"sky plate",
"mind plate",
"insect plate",
"stone plate",
"spooky plate",
"draco plate",
"dread plate",
"iron plate",
"odd incense",
"rock incense",
"full incense",
"wave incense",
"rose incense",
"luck incense",
"pure incense",
"protector",
"electirizer",
"magmarizer",
"dubious disc",
"reaper cloth",
"razor claw",
"razor fang",
"TM01",
"TM02",
"TM03",
"TM04",
"TM05",
"TM06",
"TM07",
"TM08",
"TM09",
"TM10",
"TM11",
"TM12",
"TM13",
"TM14",
"TM15",
"TM16",
"TM17",
"TM18",
"TM19",
"TM20",
"TM21",
"TM22",
"TM23",
"TM24",
"TM25",
"TM26",
"TM27",
"TM28",
"TM29",
"TM30",
"TM31",
"TM32",
"TM33",
"TM34",
"TM35",
"TM36",
"TM37",
"TM38",
"TM39",
"TM40",
"TM41",
"TM42",
"TM43",
"TM44",
"TM45",
"TM46",
"TM47",
"TM48",
"TM49",
"TM50",
"TM51",
"TM52",
"TM53",
"TM54",
"TM55",
"TM56",
"TM57",
"TM58",
"TM59",
"TM60",
"TM61",
"TM62",
"TM63",
"TM64",
"TM65",
"TM66",
"TM67",
"TM68",
"TM69",
"TM70",
"TM71",
"TM72",
"TM73",
"TM74",
"TM75",
"TM76",
"TM77",
"TM78",
"TM79",
"TM80",
"TM81",
"TM82",
"TM83",
"TM84",
"TM85",
"TM86",
"TM87",
"TM88",
"TM89",
"TM90",
"TM91",
"TM92",
"HM01",
"HM02",
"HM03",
"HM04",
"HM05",
"HM06",
"HM07",
"HM08",
"explorer kit",
"loot sack",
"rule book",
"poke radar",
"point card",
"journal",
"seal case",
"fashion case",
"seal bag",
"pal pad",
"works key",
"old charm",
"galactic key",
"red chain",
"town map",
"vs. seeker",
"coin case",
"old rod",
"good rod ",
"super rod",
"sprayduck",
"poffin case",
"bicycle",
"suite key",
"oak's letter",
"lunar wing",
"member card",
"azure flute",
"s.s. ticket",
"contest pass",
"magma stone",
"parcel",
"coupon 1",
"coupon 2",
"coupon 3",
"storage key",
"secret potion",
"gracidea",
"secret key",
"apricorn box",
"unown report",
"berry pots",
"dowsing mchn",
"blue card",
"slowpoke tail",
"clear bell",
"card key",
"basement key",
"squirt bottle",
"red scale",
"lost item",
"pass",
"machine part",
"silver wing",
"rainbow wing",
"mystery egg",
"red apricorn",
"yellow apricorn",
"blue apricorn",
"green apricorn",
"pink apricorn",
"white apricorn",
"black apricorn",
"fast ball",
"level ball",
"lure ball",
"heavy ball",
"love ball",
"friend ball",
"moon ball",
"sport ball",
"park ball",
"photo album",
"gb sounds",
"tidal bell",
"rage candy bar",
"data card 01",
"data card 02",
"data card 03",
"data card 04",
"data card 05",
"data card 06",
"data card 07",
"data card 08",
"data card 09",
"data card 10",
"data card 11",
"data card 12",
"data card 13",
"data card 14",
"data card 15",
"data card 16",
"data card 17",
"data card 18",
"data card 19",
"data card 20",
"data card 21",
"data card 22",
"data card 23",
"data card 24",
"data card 25",
"data card 26",
"data card 27",
"jade orb",
"lock capsule",
"red orb",
"blue orb",
"enigma stone"
};

const char* items2[] = {
"none",
"ball master",
"ball ultra",
"ball great",
"ball poke",
"ball safari",
"ball net",
"ball dive",
"ball nest",
"ball repeat",
"ball timer",
"ball luxury",
"ball premier",
"ball dusk",
"ball heal",
"ball quick",
"ball cherish",
"medicine potion",
"medicine antidote",
"medicine burn-heal",
"medicine ice-heal",
"medicine awakening",
"medicine paralyze-heal",
"medicine full-restore",
"medicine max-potion",
"medicine hyper-potion",
"medicine super-potion",
"medicine full-heal",
"medicine revive",
"medicine max-revive",
"medicine fresh-water",
"medicine soda-pop",
"medicine lemonade",
"medicine moomoo-milk",
"medicine energy-powder",
"medicine energy-root",
"medicine heal-powder",
"medicine revival-herb",
"medicine ether",
"medicine max-ether",
"medicine elixir",
"medicine max-elixir",
"medicine lava-cookie",
"medicine berry-juice",
"medicine sacred-ash",
"medicine hp-up",
"medicine protein",
"medicine iron",
"medicine carbos",
"medicine calcium",
"medicine rare-candy",
"medicine pp-up",
"medicine zinc",
"medicine pp-max",
"medicine old-gateau",
"battle-item guard-spec",
"battle-item dire-hit",
"battle-item x-attack",
"battle-item x-defense",
"battle-item x-speed",
"battle-item x-accuracy",
"battle-item x-sp-atk",
"battle-item x-sp-def",
"other-item poke-doll",
"other-item fluffy-tail",
"flute blue",
"flute yellow",
"flute red",
"flute black",
"flute white",
"valuable-item shoal-salt",
"valuable-item shoal-shell",
"shard red",
"shard blue",
"shard yellow",
"shard green",
"other-item super-repel",
"other-item max-repel",
"other-item escape-rope",
"other-item repel",
"evo-item sun-stone",
"evo-item moon-stone",
"evo-item fire-stone",
"evo-item thunder-stone",
"evo-item water-stone",
"evo-item leaf-stone",
"valuable-item tiny-mushroom",
"valuable-item big-mushroom",
"valuable-item pearl",
"valuable-item big-pearl",
"valuable-item stardust",
"valuable-item star-piece",
"valuable-item nugget",
"other-item heart-scale",
"other-item honey",
"mulch growth",
"mulch damp",
"mulch stable",
"mulch gooey",
"fossil root",
"fossil claw",
"fossil helix",
"fossil dome",
"fossil old-amber",
"fossil armor",
"fossil skull",
"valuable-item rare-bone",
"evo-item shiny-stone",
"evo-item dusk-stone",
"evo-item dawn-stone",
"evo-item oval-stone",
"other-item odd-keystone",
"hold-item griseous-orb",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"hold-item adamant-orb",
"hold-item lustrous-orb",
//No sprites for mail available, use generic greet-mail
"mail greet-mail",
"mail greet-mail",
"mail greet-mail",
"mail greet-mail",
"mail greet-mail",
"mail greet-mail",
"mail greet-mail",
"mail greet-mail",
"mail greet-mail",
"mail greet-mail",
"mail greet-mail",
"mail greet-mail",
"berry cheri",
"berry chesto",
"berry pecha",
"berry rawst",
"berry aspear",
"berry leppa",
"berry oran",
"berry persim",
"berry lum",
"berry sitrus",
"berry figy",
"berry wiki",
"berry mago",
"berry aguav",
"berry iapapa",
"berry razz",
"berry bluk",
"berry nanab",
"berry wepear",
"berry pinap",
"berry pomeg",
"berry kelpsy",
"berry qualot",
"berry hondew",
"berry grepa",
"berry tamato",
"berry cornn",
"berry magost",
"berry rabuta",
"berry nomel",
"berry spelon",
"berry pamtre",
"berry watmel",
"berry durin",
"berry belue",
"berry occa",
"berry passho",
"berry wacan",
"berry rindo",
"berry yache",
"berry chople",
"berry kebia",
"berry shuca",
"berry coba",
"berry payapa",
"berry tanga",
"berry charti",
"berry kasib",
"berry haban",
"berry colbur",
"berry babiri",
"berry chilan",
"berry liechi",
"berry ganlon",
"berry salac",
"berry petaya",
"berry apicot",
"berry lansat",
"berry starf",
"berry enigma",
"berry micle",
"berry custap",
"berry jaboca",
"berry rowap",
"hold-item bright-powder",
"hold-item white-herb",
"ev-item macho-brace",
"none", //EXP share
"hold-item quick-claw",
"other-item soothe-bell",
"hold-item mental-herb",
"hold-item choice-band",
"evo-item kings-rock",
"hold-item silver-powder",
"hold-item amulet-coin",
"hold-item cleanse-tag",
"hold-item soul-dew",
"evo-item deep-sea-tooth",
"evo-item deep-sea-scale",
"hold-item smoke-ball",
"hold-item everstone",
"hold-item focus-band",
"hold-item lucky-egg",
"hold-item scope-lens",
"hold-item metal-coat",
"hold-item leftovers",
"evo-item dragon-scale",
"hold-item light-ball",
"hold-item soft-sand",
"hold-item hard-stone",
"hold-item miracle-seed",
"hold-item black-glasses",
"hold-item black-belt",
"hold-item magnet",
"hold-item mystic-water",
"hold-item sharp-beak",
"hold-item poison-barb",
"hold-item never-melt-ice",
"hold-item spell-tag",
"hold-item twisted-spoon",
"hold-item charcoal",
"hold-item dragon-fang",
"hold-item silk-scarf",
"evo-item up-grade",
"hold-item shell-bell",
"incense sea",
"incense lax",
"hold-item lucky-punch",
"hold-item metal-powder",
"hold-item thick-club",
"hold-item stick",
"scarf red",
"scarf blue",
"scarf pink",
"scarf green",
"scarf yellow",
"hold-item wide-lens",
"hold-item muscle-band",
"hold-item wise-glasses",
"hold-item expert-belt",
"hold-item light-clay",
"hold-item life-orb",
"hold-item power-herb",
"hold-item toxic-orb",
"hold-item flame-orb",
"hold-item quick-powder",
"hold-item focus-sash",
"hold-item zoom-lens",
"hold-item metronome",
"hold-item iron-ball",
"hold-item lagging-tail",
"hold-item destiny-knot",
"hold-item black-sludge",
"hold-item icy-rock",
"hold-item smooth-rock",
"hold-item heat-rock",
"hold-item damp-rock",
"hold-item grip-claw",
"hold-item choice-scarf",
"hold-item sticky-barb",
"ev-item power-bracer",
"ev-item power-belt",
"ev-item power-lens",
"ev-item power-band",
"ev-item power-anklet",
"ev-item power-weight",
"hold-item shed-shell",
"hold-item big-root",
"hold-item choice-specs",
"plate flame",
"plate splash",
"plate zap",
"plate meadow",
"plate icicle",
"plate fist",
"plate toxic",
"plate earth",
"plate sky",
"plate mind",
"plate insect",
"plate stone",
"plate spooky",
"plate draco",
"plate dread",
"plate iron",
"incense odd",
"incense rock",
"incense full",
"incense wave",
"incense rose",
"incense luck",
"incense pure",
"evo-item protector",
"evo-item electirizer",
"evo-item magmarizer",
"evo-item dubious-disc",
"evo-item reaper-cloth",
"evo-item razor-claw",
"evo-item razor-fang",
"tm fighting",
"tm dragon",
"tm water",
"tm psychic",
"tm normal",
"tm poison",
"tm ice",
"tm fighting",
"tm grass",
"tm normal",
"tm fire",
"tm dark",
"tm ice",
"tm ice",
"tm normal",
"tm psychic",
"tm normal",
"tm water",
"tm grass",
"tm normal",
"tm normal",
"tm grass",
"tm steel",
"tm electric",
"tm electric",
"tm ground",
"tm normal",
"tm ground",
"tm psychic",
"tm ghost",
"tm fighting",
"tm normal",
"tm psychic",
"tm electric",
"tm fire",
"tm poison",
"tm rock",
"tm fire",
"tm rock",
"tm flying",
"tm dark",
"tm normal",
"tm normal",
"tm psychic",
"tm normal",
"tm dark",
"tm steel",
"tm psychic",
"tm dark",
"tm fire",
"tm flying",
"tm fighting",
"tm grass",
"tm normal",
"tm water",
"tm dark",
"tm electric",
"tm normal",
"tm dragon",
"tm fighting",
"tm fire",
"tm bug",
"tm dark",
"tm normal",
"tm ghost",
"tm dark",
"tm normal",
"tm normal",
"tm rock",
"tm normal",
"tm rock",
"tm ice",
"tm electric",
"tm steel",
"tm normal",
"tm rock",
"tm normal",
"tm normal",
"tm dark",
"tm rock",
"tm bug",
"tm normal",
"tm normal",
"tm poison",
"tm psychic",
"tm grass",
"tm normal",
"tm flying",
"tm bug",
"tm normal",
"tm steel",
"tm psychic",
"hm normal",
"hm flying",
"hm water",
"hm normal",
"hm water",
"hm fighting",
"hm water",
"hm normal",
"key-item explorer-kit",
"key-item loot-sack",
"key-item rule-book",
"key-item poke-radar",
"key-item point-card",
"key-item journal",
"key-item seal-case",
"key-item fashion-case",
"key-item seal-bag",
"key-item pal-pad",
"key-item works-key",
"key-item old-charm",
"key-item galactic-key",
"key-item red-chain",
"key-item town-map",
"none", //VS. SEEKER
"key-item coin-case",
"key-item old-rod",
"key-item good-rod",
"key-item super-rod",
"key-item sprayduck",
"key-item poffin-case",
"key-item bike--green",
"key-item suite-key",
"none", //OAK'S LETTER
"key-item lunar-wing",
"key-item member-card",
"key-item azure-flute",
"key-item ss-ticket",
"key-item contest-pass",
"key-item magma-stone",
"key-item parcel",
"key-item coupon-1",
"key-item coupon-2",
"key-item coupon-3",
"key-item storage-key",
"key-item secret-potion",
"key-item gracidea",
"key-item secret-key-sinnoh",
"key-item apricorn-box",
"key-item unown-report",
"key-item berry-pots",
"key-item dowsing-machine",
"key-item blue-card",
"valuable-item slowpoke-tail",
"key-item clear-bell",
"key-item card-key",
"key-item basement-key",
"key-item squirt-bottle",
"key-item red-scale",
"key-item lost-item",
"key-item pass",
"key-item machine-part",
"key-item silver-wing",
"key-item rainbow-wing",
"key-item mystery-egg",
"apricorn red",
"apricorn blue",
"apricorn yellow",
"apricorn green",
"apricorn pink",
"apricorn white",
"apricorn black",
"ball fast",
"ball level",
"ball lure",
"ball heavy",
"ball love",
"ball friend",
"ball moon",
"ball sport",
"ball park",
"key-item photo-album",
"key-item gb-sounds",
"key-item tidal-bell",
"medicine rage-candy-bar",
// DATA CARDS, IDK
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"none",
"key-item jade-orb",
"key-item lock-capsule",
"hold-item red-orb",
"hold-item blue-orb",
"key-item enigma-stone",
};

#endif